spring:
  datasource:
    url: jdbc:mysql://119.23.191.140:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB

mybatis:
      type-aliases-package: com.example.demo.dao
      mapper-locations: classpath:mapping/*Mapper.xml
logging:
  path: D:\\log
  file: D:\\log\\demo.log
  level:
    root: info

